table gold_cart_recovery_signal
	lineageTag: 319a1e9b-58e4-4feb-9bcf-db636f2f959e

	measure 'Recoverable Revenue (Today, Live)' =
			CALCULATE (
			    SUM ( gold_cart_recovery_signal[recoverable_cart_value] ),
			    gold_cart_recovery_signal[priority_score] >= 60
			)
		formatString: $ #,##0
		lineageTag: 1e9d9f50-f139-4127-87f2-cc2789478542

	measure 'Cart Priority Tier' =
			SWITCH (
			    TRUE (),
			    SELECTEDVALUE ( gold_cart_recovery_signal[priority_score] ) >= 80, "🔴 Act now",
			    SELECTEDVALUE ( gold_cart_recovery_signal[priority_score] ) >= 60, "🟠 Today",
			    SELECTEDVALUE ( gold_cart_recovery_signal[priority_score] ) >= 40, "🟡 Monitor",
			    "⚪ Low"
			)
		lineageTag: 73a8bce4-6a57-4afa-829c-bab4fa458e22


	column cart_id
		dataType: string
		lineageTag: b6e68832-b8d0-4b78-9862-06525aa3bba2
		summarizeBy: none
		sourceColumn: cart_id

	column customer_id
		dataType: string
		lineageTag: ff7b6a60-3cc3-4a4a-b3c8-4becad7b5895
		summarizeBy: none
		sourceColumn: customer_id

	column last_activity_at
		dataType: dateTime
		formatString: General Date
		lineageTag: ae14cd03-7dc2-4e18-960d-6081f9d3e262
		summarizeBy: none
		sourceColumn: last_activity_at

		annotation UnderlyingDateTimeDataType = Date

	column minutes_since_last_activity
		dataType: double
		formatString: 0.0
		lineageTag: 37ae073d-4fa2-4294-b9cf-fb4399f5c386
		summarizeBy: none
		sourceColumn: minutes_since_last_activity

	column recoverable_cart_value
		dataType: decimal
		formatString: $ #,##0.00
		lineageTag: 3dcdfea1-f79d-4ed6-bdbe-be122e6ff972
		summarizeBy: none
		sourceColumn: recoverable_cart_value

	column item_count
		dataType: int64
		formatString: 0
		lineageTag: 064d3281-426e-426c-8f08-4bdc759d5f02
		summarizeBy: none
		sourceColumn: item_count

	column recency_score
		dataType: double
		formatString: 0.0
		lineageTag: 7fe54785-becc-4332-be1e-f0b47314cf72
		summarizeBy: none
		sourceColumn: recency_score

	column value_score
		dataType: double
		formatString: 0.0
		lineageTag: de02746a-8e41-4285-9d34-4b1d8ba77162
		summarizeBy: none
		sourceColumn: value_score

	column loyalty_score
		dataType: double
		formatString: 0.0
		lineageTag: bdacbe04-9730-4c11-8216-32981d619dfa
		summarizeBy: none
		sourceColumn: loyalty_score

	column priority_score
		dataType: double
		formatString: 0.0
		lineageTag: 6cc133a4-61fd-4a45-8464-57cc7f34ab00
		summarizeBy: none
		sourceColumn: priority_score

	partition gold_cart_recovery_signal = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents(GoldPreviewFolder & "\gold_cart_recovery_signal.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"cart_id", type text}, {"customer_id", type text}, {"last_activity_at", type datetimezone}, {"minutes_since_last_activity", type number}, {"recoverable_cart_value", Currency.Type}, {"item_count", Int64.Type}, {"recency_score", type number}, {"value_score", type number}, {"loyalty_score", type number}, {"priority_score", type number}}),
				    #"Removed Zone" = Table.TransformColumns(#"Changed Type", {{"last_activity_at", DateTimeZone.RemoveZone, type datetime}})
				in
				    #"Removed Zone"
				```
